# Generated by Django 2.0.2 on 2019-06-27 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(max_length=50, verbose_name='entidad Bancaria')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=12, unique=True, verbose_name='DNI')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('conyugue', models.CharField(blank=True, max_length=100, null=True, verbose_name='conyugue')),
                ('dni_conyugue', models.CharField(blank=True, max_length=12, null=True, verbose_name='DNI Conyugue')),
                ('correo', models.EmailField(blank=True, max_length=100, null=True, verbose_name='email')),
                ('centro_laboral', models.CharField(blank=True, max_length=50, null=True, verbose_name='centro_laboral')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Banco')),
            ],
            options={
                'verbose_name': 'cliente',
                'ordering': ['apellidos', 'nombre'],
                'verbose_name_plural': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Cliente_direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=12, verbose_name='numero direccion')),
                ('orden', models.IntegerField(blank=True, default=0, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente_telefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=12, verbose_name='numero Telefono')),
                ('orden', models.IntegerField(blank=True, default=0, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='CompaniaCel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50, verbose_name='entidad Bancaria')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicion', models.CharField(max_length=20, verbose_name='estado Civil')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDireccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=50, verbose_name='Tipo de direccion')),
            ],
        ),
        migrations.CreateModel(
            name='TipoTelefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo de telefono')),
            ],
        ),
        migrations.AddField(
            model_name='cliente_telefono',
            name='tipo_numero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.TipoTelefono'),
        ),
        migrations.AddField(
            model_name='cliente_direccion',
            name='tipo_direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.TipoDireccion'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado_civil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.EstadoCivil'),
        ),
    ]
