# Generated by Django 2.0.2 on 2019-06-27 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20190627_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banco',
            options={'verbose_name': 'Entidad Bancaria', 'verbose_name_plural': 'Entidades Bancarias'},
        ),
        migrations.AlterModelOptions(
            name='companiacel',
            options={'verbose_name': 'Red Telefonica', 'verbose_name_plural': 'Redes Telefonicas'},
        ),
        migrations.AlterModelOptions(
            name='estadocivil',
            options={'verbose_name': 'Estado Civil', 'verbose_name_plural': 'Estado Civil'},
        ),
        migrations.AlterModelOptions(
            name='tipodireccion',
            options={'verbose_name': 'Tipo de direccion', 'verbose_name_plural': 'Tipos de direccion'},
        ),
        migrations.AlterModelOptions(
            name='tipotelefono',
            options={'verbose_name': 'Tipo de Telefono', 'verbose_name_plural': 'Tipos de Telefono'},
        ),
        migrations.RenameField(
            model_name='banco',
            old_name='entidad',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='companiacel',
            old_name='Nombre',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='estadocivil',
            old_name='condicion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='tipodireccion',
            old_name='Tipo',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='tipotelefono',
            old_name='tipo',
            new_name='descripcion',
        ),
    ]
